---
- name: Deploy the Alertmanager MQTT Bridge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Build program
      local_action:
        module: ansible.builtin.command
        cmd: goreleaser --snapshot --rm-dist
        args:
          chdir: "{{ playbook_dir }}/.."
      become: false

    - name: Lookup binary path from artifacts.json
      ansible.builtin.set_fact:
        binary_path: "{{ item['path'] }}"
      when: |
        item['goos'] is defined and item['goos'] == 'linux'
        and item['goarch'] is defined and item['goarch'] == 'amd64'
        and item['type'] is defined and item['type'] == 'Binary'
      loop: "{{ lookup('file', playbook_dir + '/../dist/artifacts.json') | from_json }}"
      tags: [ kiosk, goreleaser, binary, path, artifacts ]

  roles:
    - role: suhlig.simple_systemd_service
      vars:
        program:
          name: alertmanager-mqtt-proxy
          binary: "{{ binary_path }}"
          parameters: [ "--verbose" ]
          description: Alertmanager MQTT Bridge
          environment: [ "MQTT_URL='{{ mqtt_url }}'" ]
      become: true
